### ISSUE TITLE
Investigate potential fullscreen switching issue

### ISSUE THREAD

**Issue by Xenoprimate** [Egodystonic/TinyFFR#104]
Following [this](https://www.reddit.com/r/csharp/comments/1kwkf1f/show_reddit_ive_been_working_in_my_spare_time_on/mulzd6c/) comment on reddit:

> I did have some issues where switching to fullscreen would cause strange artifacts to appear but it was not consistent.

We should investigate switching back/forward to/from fullscreen and see if we can replicate this issue.

**Comment by Xenoprimate** [comment]
Thank you so much for the detailed bug report! I'll try to replicate and see if I can track down the issue. Thanks again!

**Comment by Xenoprimate** [comment]
I spent this evening trying to replicate this in various ways, on multiple monitors, multiple devices, with different resolutions and fullscreen styles, different UI scaling, even across monitors with HDR on one and not on the other.

Unfortunately I just couldn't replicate the issue. I did find another bug with the fullscreen/borderless mode switching that is now fixed at least.

I'm closing this issue for now, tentatively assuming it may have been one of the early driver issues with the nVidia 5000 series cards. However, if this is still found to be a problem I'm happy to re-open and investigate further.

**Comment by Epicguru** [comment]
Saw this pop up in my notifications so gave it another try on two different computers and screens.
Windows 11, latest NVIDIA drivers, .NET 10 preview.

- RTX 5090 4k 240Hz screen, same artifacting, seen in `Fullscreen` and `FullscreenBorderless`,
- RTX 4090 1080p 180Hz screen, entirely different computer, also severe artifacting in fullscreen and fullscreen borderless.

I also have a laptop running Ubuntu that I could test with if you want.

Full project used in tests : https://github.com/Epicguru/TinyFFRTesting

**Comment by Xenoprimate** [comment]
Thanks @Epicguru -- clearly this warrants further investigation. I'll reopen the issue and take another look.

**Comment by Xenoprimate** [comment]
@Epicguru thanks for your thorough feedback so far. 

I just pushed version `0.5.0-rc001` to NuGet:

* It fixes a build authoring error that was causing the dependency exception on Ubuntu in v0.4.
* It includes some improvements to the way the backbuffer and fullscreen switching is managed, especially regarding DPI scaling in Windows. I'm not sure if it will fix your issue but it's worth a try.
* It actually implements VSync. `WaitForVSync` on the application loop builder config still has no effect (and will be removed in v0.5.0 proper), instead you can test VSync by setting a property at the factory creation time:

```
var factory = new LocalTinyFfrFactory(
	rendererBuilderConfig: new() {
		EnableVSync = true
	}
);
```

If you are so inclined, please test this latest prerelease package and let me know how it goes. Thank you!

**Comment by Epicguru** [comment]
VSync seems to be working from brief testing, but unfortunately artifacting remains unchanged under the same conditions.  
Ubuntu still doesn't load, fails on the first dll import:
```
/home/james/Documents/Dev/C#/TinyFFRTesting/TinyFFRTesting/bin/Debug/net9.0/TinyFFRTesting
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'TinyFFR.Native' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: 
/home/james/Documents/Dev/C#/TinyFFRTesting/TinyFFRTesting/bin/Debug/net9.0/runtimes/linux-x64/native/TinyFFR.Native.so: cannot open shared object file: No such file or directory
/home/james/.dotnet/shared/Microsoft.NETCore.App/9.0.9/TinyFFR.Native.so: cannot open shared object file: No such file or directory
libc++.so.1: cannot open shared object file: No such file or directory
/home/james/.dotnet/shared/Microsoft.NETCore.App/9.0.9/libTinyFFR.Native.so: cannot open shared object file: No such file or directory
/home/james/Documents/Dev/C#/TinyFFRTesting/TinyFFRTesting/bin/Debug/net9.0/runtimes/linux-x64/native/TinyFFR.Native: cannot open shared object file: No such file or directory
/home/james/.dotnet/shared/Microsoft.NETCore.App/9.0.9/TinyFFR.Native: cannot open shared object file: No such file or directory
/home/james/Documents/Dev/C#/TinyFFRTesting/TinyFFRTesting/bin/Debug/net9.0/runtimes/linux-x64/native/libTinyFFR.Native: cannot open shared object file: No such file or directory
/home/james/.dotnet/shared/Microsoft.NETCore.App/9.0.9/libTinyFFR.Native: cannot open shared object file: No such file or directory

   at Egodystonic.TinyFFR.Factory.Local.LocalNativeUtils.SetLogNotifyDelegate( logNotifyDelegate)
```

Build folder contents:  

<img width="1501" height="1241" alt="Image" src="https://github.com/user-attachments/assets/9237b16f-d0d8-4b6b-8e8b-e71728562e61" />

Maybe worth setting up a quick `dotnet build + test` Github action to catch that stuff.

**Comment by Epicguru** [comment]
On Windows, the same artifacting is seen by default but since you mentioned the swap chain I have tested changing some NVIDIA settings and found some success.
Changing **Vulkan/OpenGL present method** from `Auto` to `Prefer layered on DXGI Swapchain` not only completely fixes the artifacting but also makes the transition to and from fullscreen (or fullscreen borderless) nearly instant whereas before it would take a second or two.

I'm not a technical graphics programmer so I can't speculate at what that means, but hopefully it helps guide you in the right direction.

<img width="898" height="873" alt="Image" src="https://github.com/user-attachments/assets/51edd1bc-00a3-45d8-ad04-94d360ae603f" />

**Comment by Xenoprimate** [comment]
@Epicguru regarding the fullscreen artifacting, does the artifacting happen if you toggle only between `NotFullscreen` and `Fullscreen` (without changing the window size)?

If it does; can you test whether changing the window size a few seconds later (after entering fullscreen mode) fixes the problem?

Thank you

**Comment by Epicguru** [comment]
Artifacting still happens when only switching in both fullscreen and borderless.  

Changing the window size after a delay once in fullscreen successfully changes the resolution but does not fix the artifacting. 
Changing the size in borderless mode does nothing but I assume that is by design.  
Depending on the resolution it changes the intensity of the artifacting but it's always there.

**Comment by Xenoprimate** [comment]
@Epicguru no problem, and no rush to retest (it's not available yet anyway).

I'm using Wayland/Kubuntu as my main dev environment myself now so hopefully I'll be able to catch any Linux-specific problems earlier going forward.
